Repository Itsabhishek7py/Welltoodit, pull requests merged in 2025-10, with the labels that each got.

#4 ADD MORE FEATURES
  README.md
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 Fix spelling mistakes in README features section
  README.md
Labels: hacktoberfest

#24 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#28 Added styling & UI in HTML Online Notepad code
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#38 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#40 Update index.html
  index.html
Labels: hacktoberfest

#43 YouTube downloader webapp
  youtube-downloader/.gitignore
  youtube-downloader/LICENSE
  youtube-downloader/README.md
  youtube-downloader/app.py
  youtube-downloader/downloader.py
  youtube-downloader/requirements.txt
  youtube-downloader/static/app.js
  youtube-downloader/static/styles.css
  youtube-downloader/templates/index.html
  youtube-downloader/tests/test_imports.py
Labels: hacktoberfest-accepted

#44 TO-DO-APP integration
  TO-DO-APP/index.html
  index.html
Labels: hacktoberfest

#45 Remove inline styles from index.html and add styles.css for better organization
  TO-DO-APP/index.html
  TO-DO-APP/styles.css
Labels: hacktoberfest

#36 Update README.md
  README.md
Labels: hacktoberfest

#46 Refactor app to use FastAPI instead of Flask for improved performance and features
  youtube-downloader/README.md
  youtube-downloader/__init__.py
  youtube-downloader/app.py
  youtube-downloader/requirements.txt
  youtube-downloader/static/app.js
  youtube-downloader/templates/index.html
  youtube-downloader/tests/conftest.py
  youtube-downloader/tests/test_path.py
Labels: hacktoberfest
